"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AnalyzeResumeRequest(_message.Message):
    """======================
    Request
    ======================
    """

    DESCRIPTOR: _descriptor.Descriptor

    FILE_BYTES_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    JD_TEXT_FIELD_NUMBER: _builtins.int
    file_bytes: _builtins.bytes
    filename: _builtins.str
    jd_text: _builtins.str
    def __init__(
        self,
        *,
        file_bytes: _builtins.bytes = ...,
        filename: _builtins.str = ...,
        jd_text: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_bytes", b"file_bytes", "filename", b"filename", "jd_text", b"jd_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AnalyzeResumeRequest: _TypeAlias = AnalyzeResumeRequest  # noqa: Y015

@_typing.final
class AnalyzeResumeResponse(_message.Message):
    """======================
    Response
    ======================
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    OVERALL_SCORE_FIELD_NUMBER: _builtins.int
    SCORE_BREAKDOWN_FIELD_NUMBER: _builtins.int
    RECRUITER_RISKS_FIELD_NUMBER: _builtins.int
    STRENGTHS_FIELD_NUMBER: _builtins.int
    TOP_FIXES_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    """Will be populated only when success is false"""
    @_builtins.property
    def overall_score(self) -> Global___OverallScore: ...
    @_builtins.property
    def score_breakdown(self) -> Global___ScoreBreakdown: ...
    @_builtins.property
    def recruiter_risks(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """3-5 bullet points"""

    @_builtins.property
    def strengths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """3-5 bullet points"""

    @_builtins.property
    def top_fixes(self) -> _containers.RepeatedCompositeFieldContainer[Global___Fix]:
        """Top 5 fix suggestions (ranked)"""

    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        overall_score: Global___OverallScore | None = ...,
        score_breakdown: Global___ScoreBreakdown | None = ...,
        recruiter_risks: _abc.Iterable[_builtins.str] | None = ...,
        strengths: _abc.Iterable[_builtins.str] | None = ...,
        top_fixes: _abc.Iterable[Global___Fix] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["overall_score", b"overall_score", "score_breakdown", b"score_breakdown"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "overall_score", b"overall_score", "recruiter_risks", b"recruiter_risks", "score_breakdown", b"score_breakdown", "strengths", b"strengths", "success", b"success", "top_fixes", b"top_fixes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AnalyzeResumeResponse: _TypeAlias = AnalyzeResumeResponse  # noqa: Y015

@_typing.final
class OverallScore(_message.Message):
    """======================
    Shared Messages
    ======================
    """

    DESCRIPTOR: _descriptor.Descriptor

    SCORE_FIELD_NUMBER: _builtins.int
    INTERPRETATION_FIELD_NUMBER: _builtins.int
    score: _builtins.int
    """0-100"""
    interpretation: _builtins.str
    """Ex: "Strong potential to get shortlisted" """
    def __init__(
        self,
        *,
        score: _builtins.int = ...,
        interpretation: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interpretation", b"interpretation", "score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OverallScore: _TypeAlias = OverallScore  # noqa: Y015

@_typing.final
class ScoreBreakdown(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMPACT_METRICS_FIELD_NUMBER: _builtins.int
    JD_ALIGNMENT_FIELD_NUMBER: _builtins.int
    OWNERSHIP_SIGNALS_FIELD_NUMBER: _builtins.int
    REMOTE_READINESS_FIELD_NUMBER: _builtins.int
    impact_metrics: _builtins.int
    """30% weight"""
    jd_alignment: _builtins.int
    """30% weight"""
    ownership_signals: _builtins.int
    """20% weight"""
    remote_readiness: _builtins.int
    """20% weight"""
    def __init__(
        self,
        *,
        impact_metrics: _builtins.int = ...,
        jd_alignment: _builtins.int = ...,
        ownership_signals: _builtins.int = ...,
        remote_readiness: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["impact_metrics", b"impact_metrics", "jd_alignment", b"jd_alignment", "ownership_signals", b"ownership_signals", "remote_readiness", b"remote_readiness"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScoreBreakdown: _TypeAlias = ScoreBreakdown  # noqa: Y015

@_typing.final
class Fix(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROBLEM_FIELD_NUMBER: _builtins.int
    WHY_IT_MATTERS_FIELD_NUMBER: _builtins.int
    IMPROVEMENT_FIELD_NUMBER: _builtins.int
    problem: _builtins.str
    why_it_matters: _builtins.str
    improvement: _builtins.str
    def __init__(
        self,
        *,
        problem: _builtins.str = ...,
        why_it_matters: _builtins.str = ...,
        improvement: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["improvement", b"improvement", "problem", b"problem", "why_it_matters", b"why_it_matters"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Fix: _TypeAlias = Fix  # noqa: Y015
