// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: resume-analyzer.proto

package resumeanalyzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileBytes     []byte                 `protobuf:"bytes,1,opt,name=file_bytes,json=fileBytes,proto3" json:"file_bytes,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	JdText        string                 `protobuf:"bytes,3,opt,name=jd_text,json=jdText,proto3" json:"jd_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResumeRequest) Reset() {
	*x = AnalyzeResumeRequest{}
	mi := &file_resume_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResumeRequest) ProtoMessage() {}

func (x *AnalyzeResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resume_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResumeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeResumeRequest) Descriptor() ([]byte, []int) {
	return file_resume_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeResumeRequest) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

func (x *AnalyzeResumeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzeResumeRequest) GetJdText() string {
	if x != nil {
		return x.JdText
	}
	return ""
}

type AnalyzeResumeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Will be populated only when success is false
	OverallScore   *OverallScore          `protobuf:"bytes,3,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	ScoreBreakdown *ScoreBreakdown        `protobuf:"bytes,4,opt,name=score_breakdown,json=scoreBreakdown,proto3" json:"score_breakdown,omitempty"`
	RecruiterRisks []string               `protobuf:"bytes,5,rep,name=recruiter_risks,json=recruiterRisks,proto3" json:"recruiter_risks,omitempty"` // 3-5 bullet points
	Strengths      []string               `protobuf:"bytes,6,rep,name=strengths,proto3" json:"strengths,omitempty"`                                 // 3-5 bullet points
	TopFixes       []*Fix                 `protobuf:"bytes,7,rep,name=top_fixes,json=topFixes,proto3" json:"top_fixes,omitempty"`                   // Top 5 fix suggestions (ranked)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeResumeResponse) Reset() {
	*x = AnalyzeResumeResponse{}
	mi := &file_resume_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResumeResponse) ProtoMessage() {}

func (x *AnalyzeResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resume_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResumeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResumeResponse) Descriptor() ([]byte, []int) {
	return file_resume_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeResumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalyzeResumeResponse) GetOverallScore() *OverallScore {
	if x != nil {
		return x.OverallScore
	}
	return nil
}

func (x *AnalyzeResumeResponse) GetScoreBreakdown() *ScoreBreakdown {
	if x != nil {
		return x.ScoreBreakdown
	}
	return nil
}

func (x *AnalyzeResumeResponse) GetRecruiterRisks() []string {
	if x != nil {
		return x.RecruiterRisks
	}
	return nil
}

func (x *AnalyzeResumeResponse) GetStrengths() []string {
	if x != nil {
		return x.Strengths
	}
	return nil
}

func (x *AnalyzeResumeResponse) GetTopFixes() []*Fix {
	if x != nil {
		return x.TopFixes
	}
	return nil
}

type OverallScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Score          int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`                  // 0-100
	Interpretation string                 `protobuf:"bytes,2,opt,name=interpretation,proto3" json:"interpretation,omitempty"` // Ex: "Strong potential to get shortlisted"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OverallScore) Reset() {
	*x = OverallScore{}
	mi := &file_resume_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallScore) ProtoMessage() {}

func (x *OverallScore) ProtoReflect() protoreflect.Message {
	mi := &file_resume_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallScore.ProtoReflect.Descriptor instead.
func (*OverallScore) Descriptor() ([]byte, []int) {
	return file_resume_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *OverallScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OverallScore) GetInterpretation() string {
	if x != nil {
		return x.Interpretation
	}
	return ""
}

type ScoreBreakdown struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ImpactMetrics    int32                  `protobuf:"varint,1,opt,name=impact_metrics,json=impactMetrics,proto3" json:"impact_metrics,omitempty"`          // 30% weight
	JdAlignment      int32                  `protobuf:"varint,2,opt,name=jd_alignment,json=jdAlignment,proto3" json:"jd_alignment,omitempty"`                // 30% weight
	OwnershipSignals int32                  `protobuf:"varint,3,opt,name=ownership_signals,json=ownershipSignals,proto3" json:"ownership_signals,omitempty"` // 20% weight
	RemoteReadiness  int32                  `protobuf:"varint,4,opt,name=remote_readiness,json=remoteReadiness,proto3" json:"remote_readiness,omitempty"`    // 20% weight
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScoreBreakdown) Reset() {
	*x = ScoreBreakdown{}
	mi := &file_resume_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdown) ProtoMessage() {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_resume_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_resume_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreBreakdown) GetImpactMetrics() int32 {
	if x != nil {
		return x.ImpactMetrics
	}
	return 0
}

func (x *ScoreBreakdown) GetJdAlignment() int32 {
	if x != nil {
		return x.JdAlignment
	}
	return 0
}

func (x *ScoreBreakdown) GetOwnershipSignals() int32 {
	if x != nil {
		return x.OwnershipSignals
	}
	return 0
}

func (x *ScoreBreakdown) GetRemoteReadiness() int32 {
	if x != nil {
		return x.RemoteReadiness
	}
	return 0
}

type Fix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problem       string                 `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
	WhyItMatters  string                 `protobuf:"bytes,2,opt,name=why_it_matters,json=whyItMatters,proto3" json:"why_it_matters,omitempty"`
	Improvement   string                 `protobuf:"bytes,3,opt,name=improvement,proto3" json:"improvement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fix) Reset() {
	*x = Fix{}
	mi := &file_resume_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fix) ProtoMessage() {}

func (x *Fix) ProtoReflect() protoreflect.Message {
	mi := &file_resume_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fix.ProtoReflect.Descriptor instead.
func (*Fix) Descriptor() ([]byte, []int) {
	return file_resume_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *Fix) GetProblem() string {
	if x != nil {
		return x.Problem
	}
	return ""
}

func (x *Fix) GetWhyItMatters() string {
	if x != nil {
		return x.WhyItMatters
	}
	return ""
}

func (x *Fix) GetImprovement() string {
	if x != nil {
		return x.Improvement
	}
	return ""
}

var File_resume_analyzer_proto protoreflect.FileDescriptor

const file_resume_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x15resume-analyzer.proto\x12\x0eresumeanalyzer\"j\n" +
	"\x14AnalyzeResumeRequest\x12\x1d\n" +
	"\n" +
	"file_bytes\x18\x01 \x01(\fR\tfileBytes\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x17\n" +
	"\ajd_text\x18\x03 \x01(\tR\x06jdText\"\xcc\x02\n" +
	"\x15AnalyzeResumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12A\n" +
	"\roverall_score\x18\x03 \x01(\v2\x1c.resumeanalyzer.OverallScoreR\foverallScore\x12G\n" +
	"\x0fscore_breakdown\x18\x04 \x01(\v2\x1e.resumeanalyzer.ScoreBreakdownR\x0escoreBreakdown\x12'\n" +
	"\x0frecruiter_risks\x18\x05 \x03(\tR\x0erecruiterRisks\x12\x1c\n" +
	"\tstrengths\x18\x06 \x03(\tR\tstrengths\x120\n" +
	"\ttop_fixes\x18\a \x03(\v2\x13.resumeanalyzer.FixR\btopFixes\"L\n" +
	"\fOverallScore\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12&\n" +
	"\x0einterpretation\x18\x02 \x01(\tR\x0einterpretation\"\xb2\x01\n" +
	"\x0eScoreBreakdown\x12%\n" +
	"\x0eimpact_metrics\x18\x01 \x01(\x05R\rimpactMetrics\x12!\n" +
	"\fjd_alignment\x18\x02 \x01(\x05R\vjdAlignment\x12+\n" +
	"\x11ownership_signals\x18\x03 \x01(\x05R\x10ownershipSignals\x12)\n" +
	"\x10remote_readiness\x18\x04 \x01(\x05R\x0fremoteReadiness\"g\n" +
	"\x03Fix\x12\x18\n" +
	"\aproblem\x18\x01 \x01(\tR\aproblem\x12$\n" +
	"\x0ewhy_it_matters\x18\x02 \x01(\tR\fwhyItMatters\x12 \n" +
	"\vimprovement\x18\x03 \x01(\tR\vimprovement2n\n" +
	"\x0eResumeAnalyzer\x12\\\n" +
	"\rAnalyzeResume\x12$.resumeanalyzer.AnalyzeResumeRequest\x1a%.resumeanalyzer.AnalyzeResumeResponseBWZUgithub.com/ManoVikram/resume-analyzer/backend/api/proto/resumeanalyzer;resumeanalyzerb\x06proto3"

var (
	file_resume_analyzer_proto_rawDescOnce sync.Once
	file_resume_analyzer_proto_rawDescData []byte
)

func file_resume_analyzer_proto_rawDescGZIP() []byte {
	file_resume_analyzer_proto_rawDescOnce.Do(func() {
		file_resume_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resume_analyzer_proto_rawDesc), len(file_resume_analyzer_proto_rawDesc)))
	})
	return file_resume_analyzer_proto_rawDescData
}

var file_resume_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_resume_analyzer_proto_goTypes = []any{
	(*AnalyzeResumeRequest)(nil),  // 0: resumeanalyzer.AnalyzeResumeRequest
	(*AnalyzeResumeResponse)(nil), // 1: resumeanalyzer.AnalyzeResumeResponse
	(*OverallScore)(nil),          // 2: resumeanalyzer.OverallScore
	(*ScoreBreakdown)(nil),        // 3: resumeanalyzer.ScoreBreakdown
	(*Fix)(nil),                   // 4: resumeanalyzer.Fix
}
var file_resume_analyzer_proto_depIdxs = []int32{
	2, // 0: resumeanalyzer.AnalyzeResumeResponse.overall_score:type_name -> resumeanalyzer.OverallScore
	3, // 1: resumeanalyzer.AnalyzeResumeResponse.score_breakdown:type_name -> resumeanalyzer.ScoreBreakdown
	4, // 2: resumeanalyzer.AnalyzeResumeResponse.top_fixes:type_name -> resumeanalyzer.Fix
	0, // 3: resumeanalyzer.ResumeAnalyzer.AnalyzeResume:input_type -> resumeanalyzer.AnalyzeResumeRequest
	1, // 4: resumeanalyzer.ResumeAnalyzer.AnalyzeResume:output_type -> resumeanalyzer.AnalyzeResumeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resume_analyzer_proto_init() }
func file_resume_analyzer_proto_init() {
	if File_resume_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resume_analyzer_proto_rawDesc), len(file_resume_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_analyzer_proto_goTypes,
		DependencyIndexes: file_resume_analyzer_proto_depIdxs,
		MessageInfos:      file_resume_analyzer_proto_msgTypes,
	}.Build()
	File_resume_analyzer_proto = out.File
	file_resume_analyzer_proto_goTypes = nil
	file_resume_analyzer_proto_depIdxs = nil
}
