// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: resume-analyzer.proto

package resumeanalyzer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResumeAnalyzer_AnalyzeResume_FullMethodName = "/resumeanalyzer.ResumeAnalyzer/AnalyzeResume"
)

// ResumeAnalyzerClient is the client API for ResumeAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeAnalyzerClient interface {
	AnalyzeResume(ctx context.Context, in *AnalyzeResumeRequest, opts ...grpc.CallOption) (*AnalyzeResumeResponse, error)
}

type resumeAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeAnalyzerClient(cc grpc.ClientConnInterface) ResumeAnalyzerClient {
	return &resumeAnalyzerClient{cc}
}

func (c *resumeAnalyzerClient) AnalyzeResume(ctx context.Context, in *AnalyzeResumeRequest, opts ...grpc.CallOption) (*AnalyzeResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResumeResponse)
	err := c.cc.Invoke(ctx, ResumeAnalyzer_AnalyzeResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeAnalyzerServer is the server API for ResumeAnalyzer service.
// All implementations must embed UnimplementedResumeAnalyzerServer
// for forward compatibility.
type ResumeAnalyzerServer interface {
	AnalyzeResume(context.Context, *AnalyzeResumeRequest) (*AnalyzeResumeResponse, error)
	mustEmbedUnimplementedResumeAnalyzerServer()
}

// UnimplementedResumeAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResumeAnalyzerServer struct{}

func (UnimplementedResumeAnalyzerServer) AnalyzeResume(context.Context, *AnalyzeResumeRequest) (*AnalyzeResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeResume not implemented")
}
func (UnimplementedResumeAnalyzerServer) mustEmbedUnimplementedResumeAnalyzerServer() {}
func (UnimplementedResumeAnalyzerServer) testEmbeddedByValue()                        {}

// UnsafeResumeAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeAnalyzerServer will
// result in compilation errors.
type UnsafeResumeAnalyzerServer interface {
	mustEmbedUnimplementedResumeAnalyzerServer()
}

func RegisterResumeAnalyzerServer(s grpc.ServiceRegistrar, srv ResumeAnalyzerServer) {
	// If the following call panics, it indicates UnimplementedResumeAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResumeAnalyzer_ServiceDesc, srv)
}

func _ResumeAnalyzer_AnalyzeResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeAnalyzerServer).AnalyzeResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeAnalyzer_AnalyzeResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeAnalyzerServer).AnalyzeResume(ctx, req.(*AnalyzeResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResumeAnalyzer_ServiceDesc is the grpc.ServiceDesc for ResumeAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResumeAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resumeanalyzer.ResumeAnalyzer",
	HandlerType: (*ResumeAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeResume",
			Handler:    _ResumeAnalyzer_AnalyzeResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resume-analyzer.proto",
}
